data_root: 'D:\CPR_extracted'
smartwatch:
  #Android sensor codes
  TYPE_ACCELEROMETER: 1
  TYPE_GYROSCOPE: 4
  TYPE_GRAVITY: 9
  TARGET_FREQ: 60
  rate_window: 5
  overlap: 0.5
  eval: True
  plot_data: False
  train_part: [0,1,2,3,4,5,6,7,8,9,10,11]
  test_part: [12,13,14,15,16,17,18,19,20,21,22,23]
  bs: 8
  get_stats: True




