data_root: 'D:\CPR_extracted'
evaluate:
  method: 'mediapipe'
  result_path: 'D:\CPR_extracted\results'
smartwatch:
  #Android sensor codes
  TYPE_ACCELEROMETER: 1
  TYPE_GYROSCOPE: 4
  TYPE_GRAVITY: 9
  TARGET_FREQ: 60
  window_len: 5
  overlap: 0.5
  eval: True
  plot_data: False
  train_part: [0,1,2,3,4,5,6,7,8,9,10,11]
  test_part: [12,13,14,15,16,17,18,19,20,21,22,23]
  bs: 32
  get_stats: False
  normalize: True
  lr: 0.001
  epochs: 10000
  eval_freq: 10
  sw_min: [-80.35959311142295,-79.25364161478956,-80.35959311142295,-80.35959311142295,-79.25364161478956,-80.35959311142295,-80.35959311142295,-79.25364161478956,-80.35959311142295]
  sw_max: [80.22816855691997,78.6352995737251,80.22816855691997,80.22816855691997,78.6352995737251,80.22816855691997,80.22816855691997,78.6352995737251,80.22816855691997]
  depth_min: 8.0
  depth_max: 61
  n_comp_min: 3.0
  n_comp_max: 36.0
  seq_model: 'LSTM'
  smooth_peaks: True
  smooth_sigma: 1
  model_save_path: 'D:\CPR_extracted\smartwatch_dataset\checkpoint\model.pth'
  mode: 'eval'   # train , eval or stats, eval_stats, peak_detection, fft
  eval_settings:
    k: 80
    height: 0.05
    checkpoint_path: 'D:\CPR_extracted\smartwatch_dataset\checkpoint\ckpt.pth'
    show_plots: True
    CPR_rate: [95,125]   #good compression rate beat per minute
    CPR_depth: [45,55]   #good compression depth in mm
    plot_save_path: 'D:\CPR_extracted\smartwatch_dataset\plots'
    peak_detection_sensor: acc  # acc, gyr or mag




