root: 'D:\hand_depth_selected'
camera: 'canon'
train_part: ['P0','P2','P6','P8','P9','P10','P13','P17','P18','P19','P20','P23']
test_part: ['P1','P3','P7','P12','P21']
train_epochs: 100
bs: 64
lr: 0.001
crop_size: 512
mode: 'normal' # 'stats': get stats of the whole dataset or 'normal': for normal training
normalize_img: True
normalize_depth: True

 

 